baseURL = "https://www.jasonscheirer.com/"
languageCode = "en-us"
title = "Jason Scheirer"
theme = "smolr"

[params]
    customCSS = ["css/jasonscheirer.css", "css/code.css"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"

  [[menu.main]]
    name = "weblog"
    url = "/weblog/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4
