baseURL = "https://www.jasonscheirer.com/"
languageCode = "en-us"
title = "Jason Scheirer"
theme = "smol"

[params]
    customCSS = ["css/jasonscheirer.css", "css/code.css"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4
