baseURL = "https://www.jasonscheirer.com/"
languageCode = "en-us"
title = "Jason Scheirer"
theme = "smolr"
paginate = 500

[params]
    customCSS = ["css/jasonscheirer.css", "css/fonts.css"]
    subtitle = "A personal web site for a computer person"
    dateFmt = "2006-01-02"

[menu]
  [[menu.main]]
    identifier = "main"
    name = "main"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "trac"
    tabWidth = 4
